M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Do 19 Okt 2023 22:21:27 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-19T22:21:27+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X118.7Y-76.1
X135.3Y-76.1
T0
M30
